source "$HOME/.cargo/env"

export NVM_DIR=$HOME/.nvm
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export GOINSTALLPATH=/usr/local/go/bin

export PATH=$PATH:$GOINSTALLPATH
