# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="ohmytheme"

plugins=(git fzf docker z)

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

export GPG_TTY=$(tty)

alias bat="batcat"

alias fixtty='reset; stty sane; tput rs1; clear; echo -e "\033c"'
